### ISSUE TITLE
Trying to install react-toolbox.com material-ui widgets

### ISSUE THREAD

**Issue by ai10** [AdamBrodzinski/awesome-stack#3]
I've spent 2 days trying to get the react-toolbox npm package working with this awesome-stack and am continually frustrated. Am stuck somewhere with HMR.  I know this is beyond the purview of your expected support; but please let me know if you might be able to help.

**Comment by AdamBrodzinski** [comment]
I might be able to check it out next week. I haven't used material-ui but i've heard it's a hassle to get going for some reason. It should be the same setup as any other webpack config if that helps.

Best of luck!
